// French copy of the atelier shell and of the agent (modes, plan, contract, mission timeline,
// approvals, mission card, status bar, palette commands). Merged into `fr.atelier`.
import type {
  AcceptanceKind,
  ApprovalScope,
  MissionFailureReason,
  MissionState,
  MissionSuspendReason,
  MissionTaskState,
  OperationClass,
  PermissionProfile,
  PermissionReason,
  ToolErrorCode,
  WorkMode,
} from "@nova/shared";

const plural = (count: number, one: string, many: string) => `${count} ${count > 1 ? many : one}`;

export const WORK_MODE_LABELS: Record<WorkMode, string> = {
  discuss: "Discuter",
  understand: "Comprendre",
  plan: "Planifier",
  build: "Construire",
  fix: "Corriger",
  verify: "Vérifier",
};

/** What each mode allows (UX.md §4.4), shown under the mode selector. */
export const WORK_MODE_HINTS: Record<WorkMode, string> = {
  discuss: "Conversation simple : Nomi ne lit ni ne modifie le projet.",
  understand: "Lecture du projet et commandes de lecture, sans aucune écriture.",
  plan: "Lecture du projet puis plan et contrat, sans rien modifier.",
  build: "Crée et modifie des fichiers dans le cadre du contrat, avec preuves.",
  fix: "Corrige un symptôme ciblé : reproduire, corriger, relancer le test.",
  verify: "Lance tests, lint ou build et rend un rapport, sans modifier le code.",
};

export const MISSION_STATE_LABELS: Record<MissionState, string> = {
  ready: "prête",
  running: "en cours",
  waiting_approval: "attend ta réponse",
  suspended: "suspendue",
  succeeded: "réussie",
  failed: "échouée",
  cancelled: "arrêtée",
};

export const TASK_STATE_LABELS: Record<MissionTaskState, string> = {
  todo: "à faire",
  running: "en cours",
  verified: "vérifiée",
  failed: "échouée",
  blocked: "bloquée",
  skipped: "ignorée",
};

export const ACCEPTANCE_LABELS: Record<AcceptanceKind, string> = {
  test_passes: "Un test passe",
  command_succeeds: "Une commande réussit",
  file_exists: "Un fichier existe",
  manual: "À confirmer par toi",
};

export const PROFILE_LABELS: Record<PermissionProfile, string> = {
  read_only: "Lecture seule",
  assisted: "Assisté",
  autonomous: "Autonome dans ce projet",
  custom: "Personnalisé",
};

export const PROFILE_HINTS: Record<PermissionProfile, string> = {
  read_only: "Nomi lit le projet ; toute écriture ou commande est refusée.",
  assisted: "Nomi demande avant d'écrire hors du contrat ou de lancer une commande notable.",
  autonomous:
    "Autonome n'est pas un accès administrateur : suppressions massives, envois et paiements demandent toujours ta confirmation.",
  custom: "Les opérations cochées ci-dessous sont permises ; le reste demande.",
};

export const OPERATION_LABELS: Record<OperationClass, string> = {
  read: "Lire des fichiers",
  write: "Créer et modifier des fichiers",
  delete: "Supprimer des fichiers",
  execute: "Lancer des commandes",
  network: "Accéder à Internet",
  git_mutation: "Modifier le dépôt Git",
  external: "Effets hors de NOVA (services connectés)",
};

export const PERMISSION_REASON_LABELS: Record<PermissionReason, string> = {
  outside_workspace: "hors du dossier du projet",
  excluded_path: "fichier exclu (sensible)",
  mode_forbids: "interdit par le mode de travail",
  contract_allows: "permis par le contrat",
  contract_forbids: "hors du contrat de mission",
  remembered_approval: "déjà autorisé",
  profile_allows: "permis par le profil",
  profile_asks: "le profil demande confirmation",
  profile_forbids: "interdit par le profil",
  always_ask: "action irréversible : confirmation à chaque fois",
  dangerous_command: "commande dangereuse",
  tainted_context: "après lecture d'un contenu non fiable",
  domain_policy: "politique Internet",
  mcp_tool_policy: "permission de l'outil du service connecté",
  isolation_unavailable: "isolation nécessaire indisponible",
  default_ask: "règle par défaut : demander",
};

/** What a failed tool call means, in French (the error's own message is written for the model). */
export const TOOL_ERROR_LABELS: Record<ToolErrorCode, string> = {
  invalid_arguments: "Demande mal formée : Nomi doit la reformuler.",
  permission_denied: "Refusé par les permissions.",
  not_found: "Introuvable.",
  conflict: "Conflit : le fichier a changé depuis sa lecture, rien n'a été écrasé.",
  outside_workspace: "Hors du dossier du projet.",
  excluded_path: "Fichier exclu (sensible).",
  too_large: "Trop volumineux.",
  timeout: "Délai dépassé.",
  cancelled: "Annulé.",
  unavailable: "Indisponible pour cette mission.",
  failed: "Échec.",
  interrupted: "Interrompue par l'arrêt de NOVA : résultat inconnu, rien n'a été relancé.",
};

export const SUSPEND_REASON_COPY: Record<MissionSuspendReason, { title: string; detail: string }> = {
  budget: {
    title: "Mission suspendue : plafond atteint",
    detail: "La mission s'est arrêtée avant l'appel suivant. Rien n'est perdu.",
  },
  daily_budget: {
    title: "Mission suspendue : plafond du jour atteint",
    detail: "Le plafond quotidien est atteint. Rien ne repartira sans toi.",
  },
  duration: { title: "Temps écoulé", detail: "Durée maximale du contrat atteinte. L'état est gardé." },
  no_progress: {
    title: "Nomi n'avance plus",
    detail: "La même action échoue en boucle : la mission est suspendue au lieu de continuer en silence.",
  },
  user: { title: "Mission en pause", detail: "Tu as mis la mission en pause. Elle reprend quand tu le décides." },
};

export const FAILURE_REASON_COPY: Record<MissionFailureReason, string> = {
  acceptance_failed: "Un critère d'acceptation n'est pas rempli.",
  provider_error: "Le fournisseur du modèle a renvoyé une erreur.",
  no_tool_support: "Ce modèle ne sait pas utiliser d'outils, nécessaire pour une mission.",
  iteration_limit: "Limite d'essais atteinte sur une étape.",
  internal: "Erreur interne de NOVA pendant la mission.",
};

export const APPROVAL_SCOPE_LABELS: Record<ApprovalScope, string> = {
  once: "Autorisé une fois",
  mission: "Autorisé pour cette mission",
  project: "Autorisé pour ce projet",
};

export const atelierCopy = {
  shell: {
    explainFailure: (shell: string, status: string) => `Explique-moi pourquoi cette commande a échoué dans ${shell}${status}, et comment la corriger :`,
    explainSelection: (shell: string) => `Explique-moi cette sortie du terminal (${shell}) :`,
    railLabel: "Espaces",
    home: "Accueil",
    conversations: "Conversations",
    files: "Fichiers",
    search: "Rechercher dans le projet",
    missions: "Missions",
    extensions: "Extensions",
    settings: "Réglages",
    explorerLabel: "Explorateur",
    workbenchLabel: "Plan de travail",
    workbenchTabs: "Documents du plan de travail",
    agentLabel: "Panneau Agent",
    dockLabel: "Dock",
    dockTabs: "Onglets du dock",
    terminal: "Terminal",
    context: "Contexte",
    editor: "Éditeur",
    closeDoc: (name: string) => `Fermer ${name}`,
    missionDoc: (title: string) => `Mission « ${title} »`,
    diffDoc: "Changements",
    checkpointsDoc: "Points de reprise",
    toggleLayout: "Basculer la disposition (conversation ↔ construction)",
    openAgent: "Afficher le panneau Agent",
    openWorkbench: "Afficher le plan de travail",
    closeWorkbench: "Masquer le plan de travail",
    openDrawer: "Ouvrir l'explorateur",
    narrowAgent: "Agent et documents",
    narrowWide: "Ouvre la fenêtre plus large pour relire le diff côte à côte.",
    offline: "Hors ligne : tu peux relire et restaurer ; les missions attendront le réseau.",
    viewLoading: "Chargement…",
    placeholderEditor: "L'éditeur n'est pas encore disponible dans cette version de NOVA.",
    placeholderTerminal: "Le terminal n'est pas encore disponible dans cette version de NOVA.",
    placeholderFiles: "L'explorateur de fichiers n'est pas encore disponible dans cette version de NOVA.",
    filesEmpty: "Aucun fichier",
    filesLoading: "Lecture du dossier…",
    filesFailed: "Dossier illisible",
    noWorkspace: "Aucun dossier ouvert",
    noWorkspaceBody: "Ouvre un dossier pour voir ses fichiers, lancer des missions et relire les changements.",
    openFolder: "Ouvrir un dossier…",
    closeFolder: "Fermer le dossier",
    folderOpened: (name: string) => `Dossier ouvert : ${name}`,
    folderOpenFailed: "Le dossier n'a pas pu être ouvert",
  },
  statusBar: {
    label: "Barre d'état",
    mode: (mode: string) => `Mode : ${mode}`,
    branch: (branch: string) => `Branche ${branch}`,
    detached: "HEAD détachée",
    changed: (count: number) => plural(count, "fichier modifié", "fichiers modifiés"),
    clean: "aucun changement",
    approvals: (count: number) => plural(count, "approbation en attente", "approbations en attente"),
    missionRunning: "Nomi travaille",
    missionWaiting: "Nomi attend ta réponse",
    missionSuspended: "Mission suspendue",
    noWorkspace: "Aucun dossier",
    display: { create: "Créer", expert: "Expert" },
    layout: { converse: "Conversation", build: "Construction" },
  },
  agent: {
    title: "Agent",
    modeLabel: "Mode de travail",
    goalLabel: "Objectif de la mission",
    goalPlaceholder: {
      understand: "Par exemple : explique-moi comment ce projet est organisé.",
      plan: "Par exemple : ajoute un formulaire de contact qui enregistre localement.",
      build: "Par exemple : crée une page d'accueil avec trois cartes de projets.",
      fix: "Par exemple : le total du panier est faux quand il y a une remise.",
      verify: "Par exemple : lance les tests et dis-moi ce qui échoue.",
    } satisfies Record<Exclude<WorkMode, "discuss">, string>,
    needsWorkspace: "Ouvre un dossier pour confier une mission à Nomi.",
    needsModel: "Choisis un modèle pour préparer une mission.",
    noTools: "Ce modèle ne sait pas utiliser d'outils, nécessaire pour une mission.",
    chooseToolModel: "Choisir un modèle avec outils",
    toolsUnknown: "Le catalogue ne dit pas si ce modèle sait utiliser des outils : la mission échouera s'il ne le sait pas.",
    planning: "Nomi prépare un plan…",
    planFailed: "Le plan n'a pas pu être produit",
    planOffline: "Hors ligne : le plan attend le réseau.",
    changeModel: "Changer de modèle",
    retry: "Réessayer",
    backToChat: "Revenir à la conversation",
    missionsHeading: "Missions de ce projet",
    noMission: "Aucune mission pour ce projet.",
    noMissionBody: "Décris un objectif ci-dessous : Nomi propose un plan et un contrat avant d'agir.",
    suggestions: "Idées de missions",
    suggestionUnderstand: "Explique-moi ce projet",
    suggestionVerify: "Lance les tests et résume les échecs",
    suggestionFix: "Trouve pourquoi un test échoue et corrige-le",
    loadingMission: "Chargement de la mission…",
    missionLoadFailed: "La mission n'a pas pu être chargée",
    thinking: "Nomi réfléchit…",
    working: "Nomi travaille",
    waiting: "Nomi attend ta réponse",
    approvalReminder: "Nomi attend ta réponse",
    seeApproval: "Voir",
    timelineLabel: "Journal de la mission",
    you: "Toi",
    nomi: "Nomi",
    streaming: "Nomi écrit…",
    menu: "Actions de la mission",
  },
  plan: {
    title: "Plan",
    summary: "Résumé",
    stepsHeading: "Étapes",
    stepTitle: (index: number) => `Étape ${index}`,
    stepTitleLabel: (index: number) => `Titre de l'étape ${index}`,
    acceptanceLabel: (index: number) => `Critère de l'étape ${index}`,
    acceptanceDetailLabel: (index: number) => `Détail du critère de l'étape ${index}`,
    moveUp: (index: number) => `Monter l'étape ${index}`,
    moveDown: (index: number) => `Descendre l'étape ${index}`,
    remove: (index: number) => `Retirer l'étape ${index}`,
    add: "Ajouter une étape",
    newStep: "Nouvelle étape",
    edited: "plan modifié",
  },
  contract: {
    title: "Ce que Nomi peut faire seul pendant cette mission",
    titleExpert: "Contrat de mission",
    folder: (path: string) => `Lire et modifier : ${path} uniquement`,
    profile: "Profil",
    operations: "Actions permises sans demander",
    hosts: "Internet : adresses permises",
    hostsHint: "Une adresse par ligne (exemple.com ou *.exemple.com). Le contrat restreint la politique Internet, il ne l'élargit jamais.",
    hostsNone: "Aucune adresse en dehors du fournisseur du modèle.",
    webSearch: "Recherche Web pendant la mission",
    webSearchHint: "La requête part vers OpenRouter puis vers le moteur de recherche ; le coût est compté à part.",
    duration: "Durée maximale (minutes)",
    budget: "Budget maximal ($)",
    isolation: "Isolation",
    isolationL0: "Processus séparé, sans isolation du système de fichiers.",
    isolationL1: "Bac à sable du système (fichiers et réseau restreints).",
    isolationL2: "Conteneur.",
    asksBefore: "Te demandera avant : supprimer un fichier, toute autre adresse Internet, toute action irréversible.",
    estimate: (range: string) => `Estimation : ${range}`,
    estimateUnknown:
      "Coût : inconnu (le catalogue ne donne pas le prix de ce modèle). Le plafond s'applique quand même, sur ce qui sera rapporté.",
    estimateOver: (cap: string) => `L'estimation dépasse le plafond (${cap}) : relève-le ou réduis le plan.`,
    assumptions: (text: string) => `Hypothèses : ${text}`,
    edit: "Modifier le contrat",
    launch: "Lancer la mission",
    launchHint: "Ctrl+Entrée pour lancer",
    cancel: "Abandonner ce plan",
    launching: "Démarrage de la mission…",
    launchFailed: "La mission n'a pas pu démarrer",
    errors: {
      noSteps: "Le plan doit contenir au moins une étape.",
      tooManySteps: "50 étapes au maximum.",
      emptyStep: (index: number) => `L'étape ${index} n'a pas de titre.`,
      budget: "Le budget doit être un montant supérieur à 0 $ et d'au plus 1 000 $.",
      duration: "La durée doit être comprise entre 1 minute et 24 heures.",
      host: (host: string) => `« ${host} » n'est pas une adresse valide (exemple.com ou *.exemple.com).`,
      tooManyHosts: "100 adresses au maximum.",
    },
  },
  timeline: {
    groupLabel: (count: number, noun: string) => `${count} ${noun}`,
    categoryNouns: {
      read: "lectures",
      search: "recherches",
      edit: "modifications",
      terminal: "commandes",
      git: "opérations Git",
      web: "accès Web",
      mcp: "appels de services",
    },
    status: {
      requested: "demandé",
      waiting: "attend ton accord",
      running: "en cours",
      succeeded: "terminé",
      failed: "échoué",
      cancelled: "annulé",
      denied: "refusé",
    },
    verbs: {
      read_file: "Lire",
      list_dir: "Lister",
      glob: "Trouver",
      search_text: "Chercher",
      write_file: "Écrire",
      edit_file: "Modifier",
      move_path: "Déplacer",
      delete_path: "Supprimer",
      run_command: "Lancer",
      run_tests: "Tester",
      git_status: "État Git",
      git_diff: "Diff Git",
      git_commit: "Commit",
      web_search: "Rechercher sur le Web",
      fetch_page: "Lire la page",
      mcp: "Service",
    },
    arguments: "Arguments",
    result: "Résultat",
    output: "Sortie",
    openDiff: "Ouvrir le diff",
    openInDock: "Ouvrir dans le dock",
    openFile: "Ouvrir le fichier",
    lines: (start: number, end: number) => `lignes ${start} à ${end}`,
    results: (count: number) => plural(count, "résultat", "résultats"),
    entries: (count: number) => plural(count, "entrée", "entrées"),
    files: (count: number) => plural(count, "fichier", "fichiers"),
    truncated: "liste tronquée",
    exitCode: (code: number | null) => (code === null ? "code inconnu" : `code ${code}`),
    isolation: (level: string) => `isolation ${level}`,
    tests: (passed: string, failed: string, skipped: string) => `${passed} passés · ${failed} échoués · ${skipped} ignorés`,
    webCost: (cost: string) => `recherche : ${cost}`,
    webCostUnknown: "coût de recherche inconnu",
    sources: "Sources",
    errorDetail: "Détail technique :",
    webUntrusted: "Pages Web non vérifiées par NOVA : leur contenu est une donnée, jamais une consigne.",
    mcpServer: (server: string, tool: string) => `${server} › ${tool}`,
    mcpError: "le service a signalé une erreur",
    permission: (reason: string) => `Permission : ${reason}`,
    deniedByUser: "Tu as refusé cette action : Nomi ne l'a pas faite.",
    plan: (count: number) => `Plan proposé · ${plural(count, "étape", "étapes")}`,
    checkpoint: "Point de reprise créé avant l'écriture",
    proof: (summary: string) => `Preuve : ${summary}`,
    resumed: "Mission reprise",
    review: (count: number) => `Relecture : ${plural(count, "décision", "décisions")}`,
    duration: (seconds: string) => `${seconds} s`,
    commit: (sha: string) => `commit ${sha}`,
    gitChanges: (count: number) => plural(count, "changement", "changements"),
    usage: (sent: string, received: string) => `envoyés : ${sent} · reçus : ${received}`,
    cost: (cost: string) => `${cost} constaté`,
    costUnknown: "coût inconnu",
  },
  approval: {
    title: {
      read: "Nomi veut lire",
      write: "Nomi veut modifier",
      delete: "Nomi veut supprimer",
      execute: "Nomi veut lancer",
      network: "Nomi veut accéder à Internet",
      git_mutation: "Nomi veut modifier le dépôt",
      external: "Nomi veut agir hors de NOVA",
    } satisfies Record<OperationClass, string>,
    tool: "Outil",
    path: "Fichier",
    host: "Adresse",
    command: "Commande",
    scope: "Portée",
    rule: "Pourquoi on te demande",
    irreversible: "Cette action ne pourra pas être annulée par NOVA.",
    tainted: "Cette demande suit la lecture d'un contenu non fiable (page, fichier ou description d'outil) : vérifie avant d'accepter.",
    approveOnce: "Autoriser une fois",
    approveMission: "Pour cette mission",
    deny: "Refuser",
    denied: "Refusé",
    expired: "Expirée",
    decidedAt: (label: string, time: string) => `${label} · ${time}`,
    shortcuts: "Ctrl+Entrée : une fois · Ctrl+Maj+Entrée : pour la mission · Échap : refuser",
    shortcutsOnce: "Ctrl+Entrée : une fois · Échap : refuser",
    decideFailed: "La réponse n'a pas pu être enregistrée",
    announce: (title: string) => `Nomi demande une confirmation : ${title}. Ctrl+Maj+A pour y aller.`,
  },
  mission: {
    heading: (title: string) => `Mission « ${title} »`,
    step: (index: number, total: number) => `étape ${index} sur ${total}`,
    stepAccessible: (index: number, title: string, state: string) => `Étape ${index}, ${title}, ${state}`,
    pause: "Mettre en pause",
    resume: "Reprendre",
    stop: "Arrêter",
    stopConfirmTitle: "Arrêter la mission ?",
    stopConfirmBody:
      "Les processus en cours sont arrêtés. Les fichiers déjà modifiés restent sur le disque : tu pourras les relire, les garder ou les annuler.",
    stopConfirm: "Arrêter la mission",
    actionFailed: "L'action sur la mission a échoué",
    duration: (text: string) => text,
    inspector: "Détail de l'étape",
    inspectorEmpty: "Choisis une étape pour voir ses faits enregistrés.",
    status: "Statut",
    acceptance: "Critère",
    files: "Fichiers",
    proofs: "Preuves",
    tools: "Appels d'outils",
    none: "—",
    openDiff: "Ouvrir le diff",
    openJournal: "Voir le journal",
    openCard: "Ouvrir la carte de mission",
    checkpoints: "Points de reprise",
    mapLabel: "Étapes de la mission",
    empty: "Aucune mission",
    emptyBody: "Décris un objectif dans l'atelier : Nomi propose un plan avant d'agir.",
    listLoading: "Chargement des missions…",
    listFailed: "Les missions n'ont pas pu être chargées",
    suspendedBanner: (title: string) => title,
    raiseCap: "Relever le plafond et reprendre",
    raiseCapLabel: "Nouveau plafond de la mission ($)",
    raiseCapInvalid: (min: string) => `Le nouveau plafond doit dépasser ${min} (au plus 1 000 $).`,
    dailyCapHint: "Le plafond du jour se règle dans Réglages › Budget ; il repart à zéro demain.",
  },
  end: {
    succeeded: "Mission terminée",
    failed: "Mission échouée",
    cancelled: "Mission arrêtée",
    cancelledBy: { user: "arrêtée par toi", system: "arrêtée par NOVA" },
    counts: (created: number, modified: number, deleted: number, moved: number) =>
      `${plural(created, "fichier créé", "fichiers créés")}, ${plural(modified, "modifié", "modifiés")}, ${plural(deleted, "supprimé", "supprimés")}${moved > 0 ? `, ${plural(moved, "déplacé", "déplacés")}` : ""}`,
    commands: (count: number) => plural(count, "commande lancée", "commandes lancées"),
    verified: "Vérifié",
    unverified: "Non vérifié",
    verifiedNone: "Rien n'a été vérifié par une exécution.",
    unverifiedNone: "Tout ce qui était prévu a été vérifié.",
    manual: "à confirmer par toi",
    costObserved: (cost: string) => `${cost} constaté`,
    costAtLeast: (cost: string, count: number) => `au moins ${cost} constaté (${plural(count, "appel sans coût rapporté", "appels sans coût rapporté")})`,
    costEstimate: (range: string) => `estimation : ${range}`,
    costUnknownEstimate: "estimation : inconnue",
    reserved: (cost: string) => `${cost} réservé`,
    billingNote: "Le montant final chez OpenRouter peut différer ; ce qui est affiché est ce que le fournisseur a rapporté.",
    review: "Relire les changements",
    noChanges: "Aucun fichier modifié.",
    approvals: (asked: number, denied: number) =>
      `${plural(asked, "confirmation demandée", "confirmations demandées")} · ${plural(denied, "refusée", "refusées")}`,
    tokens: (sent: string, received: string, lowerBound: boolean) =>
      `${lowerBound ? "au moins " : ""}${sent} jetons envoyés · ${received} reçus`,
    webCost: (cost: string, lowerBound: boolean) => `recherche Web : ${lowerBound ? "au moins " : ""}${cost}`,
    webCostUnknown: "recherche Web : coût inconnu",
    reportTitle: "Coût de la mission",
  },
  budget: {
    label: "Budget de la mission",
    spent: (amount: string) => `${amount} constaté`,
    reserved: (amount: string) => `${amount} réservé`,
    cap: (amount: string) => `plafond ${amount}`,
    noCap: "sans plafond",
    atLeast: "au moins",
    unknownCalls: (count: number) => `(${plural(count, "appel sans coût rapporté", "appels sans coût rapporté")})`,
    suspended: "suspendue",
    valueText: (spent: string, cap: string | null, atLeast: boolean) =>
      `${atLeast ? "au moins " : ""}${spent} constaté${cap ? ` sur un plafond de ${cap}` : ", sans plafond"}`,
  },
  commands: {
    nomiMenu: "Ouvrir le menu de Nomi",
    groups: {
      app: "Application",
      conversation: "Conversation",
      model: "Modèle",
      settings: "Réglages",
      view: "Affichage",
      layout: "Disposition",
      focus: "Zones",
      file: "Fichiers",
      review: "Relecture",
      mission: "Mission",
      approval: "Approbations",
      terminal: "Terminal",
      help: "Aide",
    },
    openFolder: "Ouvrir un dossier",
    closeFolder: "Fermer le dossier",
    quickOpen: "Ouvrir rapidement un fichier",
    toggleLayout: "Basculer la disposition conversation ↔ construction",
    toggleDisplay: "Basculer l'affichage Créer ↔ Expert",
    toggleExplorer: "Afficher ou masquer l'explorateur",
    toggleAgent: "Afficher ou masquer le panneau Agent",
    toggleDock: "Afficher ou masquer le dock",
    showFiles: "Afficher les fichiers",
    showMissions: "Afficher les missions",
    showConversations: "Afficher les conversations",
    openExtensions: "Ouvrir les extensions (serveurs MCP)",
    openChanges: "Relire les changements de la mission",
    openMissionCard: "Ouvrir la carte de mission",
    openCheckpoints: "Ouvrir les points de reprise",
    pauseMission: "Mettre la mission en pause",
    resumeMission: "Reprendre la mission",
    stopMission: "Arrêter la mission",
    goToApproval: "Aller à l'approbation en attente",
    showTimeline: "Afficher le journal de la mission",
    nextZone: "Zone suivante",
    previousZone: "Zone précédente",
    focusComposer: "Écrire à Nomi",
    setMode: (mode: string) => `Mode : ${mode}`,
    openBudget: "Réglages : budget",
    openPermissions: "Réglages : permissions",
    openInternet: "Réglages : Internet",
    openAudit: "Réglages : journal d'audit",
    askNomi: (query: string) => `Demander à Nomi : « ${query} »`,
    goToLine: (line: number) => `Aller à la ligne ${line}`,
    goToLineUnavailable: "Ouvre un fichier dans l'éditeur pour aller à une ligne.",
    noWorkspace: "Ouvre d'abord un dossier.",
    noMission: "Aucune mission en cours.",
    noApproval: "Aucune approbation en attente.",
    prefixes: "> commandes · @ fichiers · # missions · / modes · : ligne",
    modesGroup: "Modes de travail",
    modesEmpty: "Aucun mode ne correspond.",
    filesGroup: "Fichiers",
    missionsGroup: "Missions",
    filesLoading: "Recherche de fichiers…",
    filesEmpty: "Aucun fichier ne correspond.",
    missionsEmpty: "Aucune mission ne correspond.",
    lineHint: "Tape un numéro de ligne, par exemple :42",
  },
  home: {
    openFolderTitle: "Ouvrir un dossier",
    openFolderBody: "Choisir un dossier sur cet ordinateur · NOVA n'y touchera pas sans te le dire.",
    openFolderAction: "Ouvrir un dossier…",
    currentFolder: (name: string) => `Dossier ouvert : ${name}`,
    facts: (stack: string) => `Projet détecté : ${stack}`,
    factsUnknown: "Pile technique non détectée",
    git: (branch: string) => `Git détecté (branche ${branch})`,
    gitNone: "Pas de dépôt Git : les points de reprise servent de retour arrière.",
    nothingSent: "Rien n'a été envoyé.",
    goToAgent: "Confier une mission à Nomi",
    recentTitle: "Dossiers récents",
    reopen: (name: string) => `Rouvrir ${name}`,
  },
  context: {
    inspectorTitle: "Ce qui part avec ce message",
    destination: (provider: string) => `Vers OpenRouter → ${provider}`,
    mentionsLabel: "Éléments ajoutés",
    mentionFile: (path: string) => `fichier ${path}`,
    mentionFolder: (path: string) => `dossier ${path}`,
    mentionUrl: (url: string) => `page ${url}`,
    removeMention: (label: string) => `Retirer ${label}`,
    noMention: "Aucun fichier joint. Tape @ pour ajouter un fichier, un dossier ou une adresse.",
    mentionHint: "@fichier, @dossier/ ou @https://…",
    webToggle: "Web",
    webOn: "Recherche Web permise pour cette mission",
    webOnChat: "Recherche Web activée : les sources citées sont ajoutées à la réponse",
    chatAttaches:
      "Ces éléments partent avec ce message : NOVA les lit dans ton dossier (fichiers sensibles refusés, message bloqué si un secret y figure).",
    webOff: "Recherche Web désactivée",
    alreadyAllowed: "Déjà autorisé dans cette mission",
    inspectorToggle: "Ce qui part",
    goalTokens: (count: string) => `Objectif : ≈ ${count} jetons (estimation)`,
    destinationModel: (model: string) => `Vers OpenRouter → ${model} (fournisseur choisi par OpenRouter)`,
    retentionDeny: "Sans conservation : seuls les fournisseurs qui ne gardent pas tes messages sont utilisés.",
    retentionAllow: "Conservation autorisée : certains fournisseurs peuvent garder tes messages.",
    missionReads: "Nomi lira ces éléments pendant la mission, avec les permissions du contrat : leur contenu ne part qu'au moment de la lecture.",
    pickerLabel: "Éléments à mentionner",
    pickerSearching: "Recherche de fichiers…",
    pickerEmpty: "Aucun fichier ne correspond.",
    pickerFailed: "La recherche de fichiers a échoué.",
    pickerHint: "↑ ↓ pour choisir · Entrée pour ajouter · Échap pour fermer",
    webHint: "Nomi pourra chercher sur le Web pendant la mission (coût compté à part).",
  },
} as const;
