// French copy of the change review (diff) and checkpoints documents (A10/A11). Merged into `fr.diff`.
import type { CheckpointReason } from "@nova/shared";

const plural = (count: number, one: string, many: string) => `${count} ${count > 1 ? many : one}`;

export const CHECKPOINT_REASON_LABELS: Record<CheckpointReason, string> = {
  tool_write: "avant une écriture de Nomi",
  user_replace: "avant un remplacement",
  before_restore: "avant retour",
  manual: "manuel",
};

export const diffCopy = {
  review: {
    title: "Changements",
    label: "Relecture des changements",
    header: (files: number, additions: number, deletions: number, mission: string) =>
      `Diff — ${plural(files, "fichier", "fichiers")} · +${additions} −${deletions} · mission « ${mission} »`,
    summaryCreate: (created: number, modified: number, deleted: number) =>
      `${plural(modified, "fichier modifié", "fichiers modifiés")} · ${plural(created, "créé", "créés")} · ${plural(deleted, "supprimé", "supprimés")}`,
    keepAll: "Tout garder",
    revertAll: "Tout annuler",
    revertAllTitle: "Annuler tous les changements de la mission ?",
    revertAllBody:
      "Ces fichiers reviennent à leur état d'avant la mission. Si tu en as modifié un depuis, rien n'est écrasé : il est signalé.",
    revertAllConfirm: "Tout annuler",
    keep: "Garder",
    restore: "Restaurer",
    remove: "Supprimer",
    see: "Voir",
    hide: "Masquer",
    keepHunk: "Garder ce bloc",
    revertHunk: "Annuler ce bloc",
    resetHunk: "Remettre en attente",
    apply: (count: number) => `Appliquer ${plural(count, "décision", "décisions")}`,
    applying: "Application…",
    applied: (count: number) => `${plural(count, "décision appliquée", "décisions appliquées")}`,
    applyFailed: "Les décisions n'ont pas pu être appliquées",
    change: { created: "créé", modified: "modifié", deleted: "supprimé", moved: "déplacé" },
    moved: (from: string, to: string) => `${from} → ${to}`,
    verifiedBy: (summary: string) => `Vérifié par : ${summary}`,
    unverified: "Non vérifié",
    proofTestPassed: "test passé",
    proofTestFailed: "test échoué",
    proofCommandPassed: "commande réussie",
    proofCommandFailed: "commande échouée",
    proofNone: "aucun test",
    kept: "gardé",
    reverted: "annulé",
    partial: (kept: number, total: number) => `${kept} sur ${total} gardés`,
    alreadyDecided: { kept: "gardé", reverted: "annulé" },
    conflict: "Ce fichier a changé depuis la mission · rien n'a été écrasé.",
    toggleFile: (path: string, open: boolean) => (open ? `Replier ${path}` : `Déplier ${path}`),
    hunkRegion: (index: number, total: number, start: number, end: number) =>
      `bloc ${index} sur ${total}, lignes ${start} à ${end}`,
    lineAdded: "ajouté",
    lineRemoved: "supprimé",
    showMore: (count: number) => `Afficher ${plural(count, "ligne de plus", "lignes de plus")}`,
    unified: "Unifié",
    sideBySide: "Côte à côte",
    viewLabel: "Présentation du diff",
    sideBySideNarrow: "Le côte à côte demande un plan de travail plus large (1 100 px).",
    sideBySideUnavailable: "Côte à côte indisponible : le fichier a changé depuis le calcul du diff.",
    sideBySideLoading: "Préparation du côte à côte…",
    keys: "j/k : bloc suivant/précédent · a : garder · x : annuler · u : côte à côte · o : ouvrir",
    empty: "Aucun changement à relire",
    emptyBody: "Cette mission n'a modifié aucun fichier.",
    loading: "Calcul des changements…",
    error: "Diff impossible : le fichier a changé pendant le calcul",
    recompute: "Recalculer",
    noGit: "Diff indisponible sans Git pour l'instant : les points de reprise permettent quand même de restaurer.",
    gitNote:
      "Le diff compare le disque au dernier commit : il peut aussi contenir tes propres modifications non enregistrées.",
    truncated: "Diff tronqué (plus de 1 Mo) : seule une partie est affichée.",
    missing: {
      binary: "Fichier binaire : pas de diff texte.",
      no_git: "Pas de diff sans Git.",
      no_change: "Aucune différence avec le dernier commit.",
      unreadable: "Fichier illisible.",
    },
    narrow: "Ouvre la fenêtre plus large pour relire le diff.",
    missionMissing: "Cette mission n'est pas chargée.",
    leaveTitle: "Garder les blocs acceptés et abandonner le reste ?",
    leaveBody: "Les blocs gardés sont enregistrés ; les autres restent en attente de décision.",
    leaveConfirm: "Garder les blocs acceptés",
    leaveCancel: "Continuer la relecture",
    announceKept: "Gardé",
    announceReverted: "Annulé",
    pendingFiles: (count: number) => `${plural(count, "fichier en attente", "fichiers en attente")} de décision`,
  },
  checkpoints: {
    title: "Points de reprise",
    label: "Historique des points de reprise",
    empty: "Aucun point de reprise pour l'instant.",
    emptyBody: "NOVA en crée un avant chaque écriture de Nomi et avant chaque retour.",
    loading: "Lecture des points de reprise…",
    failed: "Les points de reprise n'ont pas pu être lus",
    needsWorkspace: "Ouvre un dossier pour voir ses points de reprise.",
    reason: CHECKPOINT_REASON_LABELS,
    files: (count: number) => plural(count, "fichier", "fichiers"),
    fileChange: { created: "créé", modified: "modifié", deleted: "supprimé" },
    restoreFile: "Restaurer ce fichier",
    restoreFileNamed: (path: string) => `Restaurer ${path}`,
    restored: (path: string) => `${path} restauré`,
    restoreAll: "Revenir à ce point",
    restoreAllTitle: (label: string) => `Revenir à « ${label} » ?`,
    restoreAllBody: (count: number) =>
      `${plural(count, "fichier reviendra", "fichiers reviendront")} à leur état de ce moment. Les modifications faites depuis, y compris les tiennes, sont enregistrées dans un nouveau point de reprise « avant retour » pour ne rien perdre.`,
    restoreAllConfirm: "Revenir",
    restoreAllDone: (restored: number, conflicts: number) =>
      `${plural(restored, "fichier restauré", "fichiers restaurés")}${conflicts > 0 ? ` · ${plural(conflicts, "conflit", "conflits")}, rien d'écrasé` : ""}`,
    safety: "Point de reprise « avant retour » créé : ce retour est lui-même annulable.",
    restoreFailed: "La restauration a échoué",
    conflictTitle: "Ce fichier a changé depuis ce point de reprise",
    conflictBody: "Rien n'a été écrasé. Tu peux garder ta version, ou comparer les deux dans l'éditeur.",
    keepMine: "Garder ma version",
    compare: "Comparer",
    conflictItem: (path: string) => `${path} : modifié depuis, rien d'écrasé`,
    restoredItem: (path: string) => `${path} : restauré`,
  },
} as const;
