// French copy of the Extensions space (MCP servers manager, M3/M5). Merged into `fr.extensions`.
import type { McpServerState, McpToolPermission } from "@nova/shared";

const plural = (count: number, one: string, many: string) => `${count} ${count > 1 ? many : one}`;

export const MCP_STATE_LABELS: Record<McpServerState, string> = {
  connected: "connecté",
  stopped: "arrêté",
  starting: "connexion…",
  error: "en erreur",
  timeout: "injoignable (délai dépassé)",
  disabled: "désactivé",
};

export const MCP_PERMISSION_LABELS: Record<McpToolPermission, string> = {
  allow: "Autoriser",
  ask: "Demander",
  deny: "Refuser",
};

export const extensionsCopy = {
  title: "Extensions",
  serversHeading: "Services connectés (MCP)",
  listLabel: "Serveurs MCP",
  add: "Ajouter un serveur",
  loading: "Chargement des serveurs…",
  empty: "Aucun service connecté.",
  emptyBody: "Ajoute un serveur MCP (commande locale ou adresse distante) pour donner de nouveaux outils à Nomi.",
  loadFailed: "Les serveurs n'ont pas pu être chargés",
  unavailable: "Le gestionnaire de services n'est pas disponible pour l'instant dans NOVA.",
  retry: "Réessayer",
  selectHint: "Choisis un serveur pour voir son état, ses outils et leurs permissions.",
  transportStdio: "stdio",
  transportHttp: "https",
  tools: (count: number | null) => (count === null ? "outils inconnus" : plural(count, "outil", "outils")),
  scopeGlobal: "global",
  scopeWorkspace: "ce projet",
  // Detail
  status: "État",
  protocol: (version: string) => `protocole ${version}`,
  lastError: "Dernière erreur",
  transport: "Transport",
  command: "Commande",
  args: "Arguments",
  argsHidden: (count: number) => plural(count, "argument masqué", "arguments masqués"),
  argsNone: "aucun argument",
  showArgs: "Afficher",
  hideArgs: "Masquer",
  url: "Adresse",
  secrets: (count: number) => plural(count, "valeur secrète dans le coffre", "valeurs secrètes dans le coffre"),
  test: "Tester la connexion",
  testDone: "Test terminé",
  testFailed: "Le test de connexion a échoué",
  disable: "Désactiver",
  enable: "Activer",
  toggled: (enabled: boolean) => (enabled ? "Serveur activé" : "Serveur désactivé"),
  toggleFailed: "Le serveur n'a pas pu être modifié",
  edit: "Modifier",
  remove: "Retirer",
  removeTitle: (name: string) => `Retirer « ${name} » ?`,
  removeDescription:
    "Le serveur et ses permissions seront retirés de NOVA ; ses secrets sont effacés du coffre. Le programme ou le service lui-même n'est pas désinstallé.",
  removed: "Serveur retiré",
  removeFailed: "Le serveur n'a pas pu être retiré",
  journal: "Journal",
  journalHint: "Dernières lignes de la sortie d'erreur du serveur (secrets masqués).",
  journalEmpty: "Le serveur n'a rien écrit sur sa sortie d'erreur.",
  journalNone: "Lance « Tester la connexion » pour lire les dernières lignes du serveur.",
  // Tools
  toolsHeading: "Outils et permissions",
  toolsLoading: "Lecture des outils…",
  toolsFailed: "Les outils n'ont pas pu être lus",
  toolsEmpty: "Ce serveur n'annonce aucun outil (ou n'est pas connecté).",
  permissionScope: "Règles appliquées",
  permissionScopeGlobal: "Pour tous les projets",
  permissionScopeWorkspace: (name: string) => `Pour ${name}`,
  permissionLabel: (tool: string) => `Permission de ${tool}`,
  permissionSaved: "Permission enregistrée",
  permissionFailed: "La permission n'a pas été enregistrée",
  notOffered: "non proposé au modèle : nom trop long",
  denied: "refusé",
  hintReadOnly: "indice : lecture seule",
  hintDestructive: "indice : destructif",
  hintOpenWorld: "indice : agit hors de ta machine",
  hintsNote: "Les indices viennent du serveur : ce ne sont pas des preuves.",
  untrustedFrame: "Texte fourni par le serveur, non vérifié par NOVA",
  describedBy: "Décrit par le serveur :",
  noDescription: "Aucune description fournie.",
  imperativeWarning:
    "Cette description contient des consignes adressées au modèle : traitée comme du texte, jamais comme une règle.",
  // Form
  formAddTitle: "Ajouter un serveur MCP",
  formEditTitle: (name: string) => `Modifier « ${name} »`,
  formIntro:
    "Les services connectés reçoivent ce que Nomi leur envoie. Les valeurs secrètes partent au coffre de ton système et ne sont plus jamais affichées.",
  name: "Nom",
  scope: "Portée",
  transportLabel: "Transport",
  transportStdioLabel: "Commande locale (stdio)",
  transportHttpLabel: "Adresse distante (HTTP)",
  commandLabel: "Commande",
  commandHint: "Par exemple : npx, uvx, node ou un chemin absolu.",
  argsLabel: "Arguments",
  argsHint: "Un argument par ligne.",
  urlLabel: "Adresse du serveur",
  envHeading: "Variables d'environnement",
  headersHeading: "En-têtes HTTP",
  addEnv: "Ajouter une variable",
  addHeader: "Ajouter un en-tête",
  rowName: "Nom",
  rowValue: "Valeur",
  rowSecret: "Secret",
  rowRemove: (name: string) => `Retirer ${name || "la ligne"}`,
  secretKept: (hint: string) => `Secret conservé (••••${hint}) — saisis une valeur pour le remplacer`,
  enabled: "Activer ce serveur",
  save: "Enregistrer",
  saved: "Serveur enregistré",
  saveFailed: "Le serveur n'a pas été enregistré",
  cancel: "Annuler",
  errors: {
    name: "Donne un nom au serveur.",
    command: "Indique la commande à lancer.",
    url: "Adresse invalide : elle doit commencer par https:// (ou http://).",
    envName: "Nom de variable invalide (lettres, chiffres et _ ; pas de chiffre au début).",
    headerName: "Nom d'en-tête invalide (lettres, chiffres et -).",
    duplicate: "Ce nom est déjà utilisé.",
    secretEmpty: "Saisis la valeur secrète.",
    tooLong: "Valeur trop longue.",
    invalid: "La configuration n'est pas valide.",
  },
} as const;
