// Every user-facing string of the renderer (French). Code and comments stay in English.
import type { ConnectionState, IpcErrorCode, KeyStorage, ProviderErrorCode, VaultLevel } from "@nova/shared";
import { atelierCopy } from "./fr-atelier";
import { diffCopy } from "./fr-diff";
import { extensionsCopy } from "./fr-extensions";
import { atelierSettingsCopy } from "./fr-settings-atelier";

export interface ErrorCopy {
  title: string;
  detail: string;
  /** Label of the follow-up action, when one helps. */
  action: string | null;
}

export const PROVIDER_ERROR_COPY: Record<ProviderErrorCode, ErrorCopy> = {
  no_key: {
    title: "Aucune clé OpenRouter",
    detail: "Ajoute une clé dans Réglages › Fournisseurs pour discuter avec un modèle.",
    action: "Ajouter une clé",
  },
  invalid_key: {
    title: "La clé OpenRouter est refusée",
    detail: "OpenRouter ne reconnaît pas cette clé : elle a peut-être été révoquée ou mal copiée.",
    action: "Remplacer la clé",
  },
  insufficient_credits: {
    title: "Crédits OpenRouter insuffisants",
    detail: "Ton solde ne couvre pas cette requête. Recharge ton crédit sur openrouter.ai, puis réessaie.",
    action: "Ouvrir la page des crédits",
  },
  forbidden: {
    title: "Requête refusée par OpenRouter",
    detail: "La clé n'a pas le droit d'utiliser ce modèle, ou la modération a bloqué le contenu.",
    action: "Changer de modèle",
  },
  rate_limited: {
    title: "Trop de requêtes",
    detail: "Le fournisseur limite le débit. NOVA ne relance jamais seul : réessaie après le délai.",
    action: "Réessayer",
  },
  timeout: {
    title: "Le modèle ne répond pas",
    detail: "Aucune réponse dans le délai prévu. Le modèle est peut-être surchargé.",
    action: "Réessayer",
  },
  not_found: {
    title: "Modèle introuvable",
    detail:
      "Ce modèle n'existe plus, ou aucun de ses fournisseurs ne respecte ta politique de conservation des données (Réglages › Confidentialité).",
    action: "Changer de modèle",
  },
  model_unavailable: {
    title: "Modèle indisponible",
    detail: "Le fournisseur de ce modèle ne répond pas pour l'instant. Réessaie plus tard ou choisis un autre modèle.",
    action: "Changer de modèle",
  },
  no_provider: {
    title: "Aucun fournisseur disponible",
    detail: "Aucun fournisseur ne peut servir ce modèle pour l'instant. Réessaie dans un moment ou choisis un autre modèle.",
    action: "Changer de modèle",
  },
  bad_request: {
    title: "Requête refusée",
    detail: "Le fournisseur n'a pas accepté la requête. La conversation est peut-être trop longue pour ce modèle.",
    action: "Changer de modèle",
  },
  network: {
    title: "Pas de connexion au fournisseur",
    detail: "NOVA n'arrive pas à joindre OpenRouter. Vérifie ta connexion Internet.",
    action: "Réessayer",
  },
  stream_interrupted: {
    title: "La réponse a été coupée en route",
    detail: "La connexion s'est interrompue avant la fin. Le texte reçu est conservé.",
    action: "Réessayer",
  },
  provider_error: {
    title: "Erreur du fournisseur",
    detail: "Le fournisseur a renvoyé une erreur pendant la génération. Le texte reçu est conservé.",
    action: "Réessayer",
  },
  key_unreadable: {
    title: "Clé enregistrée illisible",
    detail:
      "NOVA n'arrive plus à déchiffrer ta clé : le trousseau du système est peut-être verrouillé ou a été réinitialisé. Déverrouille-le ou saisis la clé à nouveau.",
    action: "Saisir la clé à nouveau",
  },
  truncated: {
    title: "Réponse coupée à sa longueur maximale",
    detail:
      "Le modèle a atteint la limite de longueur de sa réponse. Le texte reçu est conservé : réessaie, ou demande-lui de continuer.",
    action: "Réessayer",
  },
  filtered: {
    title: "Réponse bloquée par le filtre du fournisseur",
    detail:
      "Le filtre de contenu du fournisseur a arrêté la réponse. Reformule ta demande, ou choisis un autre modèle.",
    action: "Changer de modèle",
  },
  empty_response: {
    title: "Le modèle n'a rien répondu",
    detail: "La réponse est arrivée vide. Réessaie ; si ça se répète, choisis un autre modèle.",
    action: "Réessayer",
  },
  aborted: {
    title: "Génération arrêtée",
    detail: "Tu as arrêté la génération. Le texte reçu est conservé.",
    action: "Relancer",
  },
  unknown: {
    title: "Erreur inattendue",
    detail: "Quelque chose a échoué sans explication du fournisseur.",
    action: "Réessayer",
  },
};

export const IPC_ERROR_COPY: Record<IpcErrorCode, string> = {
  invalid_request: "La demande a été refusée : ses données ne sont pas valides.",
  not_found: "Élément introuvable : il a peut-être été supprimé.",
  conflict: "Action impossible pour l'instant : une génération ou une mission est en cours ici. Arrête-la d'abord.",
  vault_unavailable: "Ce mode de stockage n'est pas disponible sur ce système.",
  no_key: "Aucune clé OpenRouter n'est enregistrée.",
  key_unreadable:
    "Ta clé enregistrée ne peut pas être lue : le trousseau du système est verrouillé ou a changé. Déverrouille-le, ou saisis ta clé à nouveau.",
  provider: "Le fournisseur a renvoyé une erreur.",
  unavailable: "Cette fonction n'est pas disponible pour l'instant dans NOVA.",
  internal: "Erreur interne de NOVA. Réessaie ; si ça persiste, consulte les journaux (Réglages › Diagnostics).",
};

/** Follow-up for IPC failures that the user can fix in Réglages › Fournisseurs. */
export const IPC_ERROR_ACTIONS: Partial<Record<IpcErrorCode, string>> = {
  no_key: "Ajouter une clé",
  key_unreadable: "Saisir la clé à nouveau",
};

/** Secondary hint for `no_provider`: the data policy can also narrow the providers of a model. */
export const NO_PROVIDER_PRIVACY_HINT =
  "Ta politique de conservation des données écarte aussi certains fournisseurs : elle peut en être la cause.";

export function rateLimitedTitle(seconds: number): string {
  return `Trop de requêtes — réessaie dans ${seconds} s`;
}

export const CONNECTION_STATE_LABELS: Record<ConnectionState, string> = {
  absent: "Aucune clé",
  unverified: "Clé non vérifiée",
  valid: "Clé vérifiée",
  invalid: "Clé refusée",
  error: "Vérification impossible",
};

export const KEY_STORAGE_LABELS: Record<KeyStorage, string> = {
  vault: "Coffre du système",
  "weak-vault": "Protection faible",
  session: "Cette session uniquement",
};

export const VAULT_LEVEL_COPY: Record<VaultLevel, { label: string; detail: string }> = {
  os: {
    label: "Coffre du système",
    detail: "Les clés enregistrées dans le coffre sont chiffrées par le trousseau de ton système d'exploitation.",
  },
  weak: {
    label: "Protection faible",
    detail:
      "Aucun trousseau système n'est disponible : une clé enregistrée serait seulement masquée, pas vraiment chiffrée.",
  },
  unavailable: {
    label: "Chiffrement indisponible",
    detail: "NOVA ne peut pas chiffrer de clé ici : une clé n'est gardée que pour la session en cours.",
  },
};

export const fr = {
  app: {
    booting: "Démarrage de NOVA…",
    bootFailed: "NOVA n'a pas pu charger ses données",
    retry: "Réessayer",
    unknown: "inconnu",
    close: "Fermer",
    cancel: "Annuler",
    save: "Enregistrer",
    copied: "Copié",
  },
  format: {
    justNow: "à l'instant",
    tokens: (count: string) => `${count} jetons`,
    kiloTokens: (count: string) => `${count} k jetons`,
    megaTokens: (count: string) => `${count} M jetons`,
  },
  nav: {
    label: "Navigation principale",
    newConversation: "Nouvelle conversation",
    searchLabel: "Rechercher une conversation",
    searchPlaceholder: "Rechercher…",
    conversationsHeading: "Conversations",
    loading: "Chargement des conversations…",
    loadFailed: "Les conversations n'ont pas pu être chargées",
    empty: "Aucune conversation pour l'instant. Lance-toi depuis l'accueil.",
    emptySearch: (query: string) => `Aucune conversation ne contient « ${query} ».`,
    olderExist: "Des conversations plus anciennes existent : utilise la recherche.",
    moreResults: "D'autres conversations correspondent : précise ta recherche.",
    failedMarker: "Dernière réponse en échec",
    streaming: "Génération en cours",
    rename: "Renommer",
    remove: "Supprimer",
    renameNamed: (title: string) => `Renommer « ${title} »`,
    removeNamed: (title: string) => `Supprimer « ${title} »`,
    home: "Accueil",
    settings: "Réglages",
    openDrawer: "Ouvrir la navigation",
    drawerTitle: "Navigation",
  },
  conversation: {
    renameTitle: "Renommer la conversation",
    renameLabel: "Titre",
    deleteTitle: (title: string) => `Supprimer « ${title} » ?`,
    deleteDescription:
      "Les messages de cette conversation seront effacés de cet appareil. Cette action est définitive.",
    deleteConfirm: "Supprimer",
    deleted: "Conversation supprimée",
    renamed: "Conversation renommée",
    untitled: "Nouvelle conversation",
  },
  nomi: {
    starting: "Démarrage",
    startingDetail: "Lecture de l'état de la connexion…",
    noKey: "Pas encore connecté",
    noKeyDetail: "Ajoute une clé OpenRouter pour commencer.",
    invalidKey: "Clé refusée",
    invalidKeyDetail: "OpenRouter refuse la clé : remplace-la dans Réglages.",
    offline: "Hors ligne",
    offlineDetail: "Pas de réseau : les messages ne partiront pas.",
    thinking: "Nomi réfléchit…",
    waitingDetail: "Requête envoyée, en attente du modèle.",
    reasoningDetail: "Le modèle raisonne avant de répondre.",
    working: "Nomi écrit…",
    writingDetail: "La réponse arrive.",
    success: "Réponse terminée",
    error: "Quelque chose a échoué",
    errorDetail: "Le détail est affiché sous le message.",
    errorElsewhere: (title: string) => `« ${title} » a échoué.`,
    stopped: "Génération arrêtée",
    idle: "Nomi est disponible",
    verified: (relative: string) => `Connecté à OpenRouter · clé vérifiée ${relative}`,
    unverified: "Clé non vérifiée",
    checkFailed: "Clé non vérifiée · le dernier test a échoué",
    openSettings: "Ouvrir les réglages du compagnon",
  },
  home: {
    title: "Atelier",
    subtitle: "Une idée, une question, un brouillon : Nomi t'aide à en faire quelque chose.",
    newIdea: "Nouvelle idée",
    newIdeaLabel: "Décris ton idée",
    newIdeaPlaceholder: "Par exemple : aide-moi à structurer un article sur…",
    resume: "Reprendre",
    resumeEmpty: "Tes conversations apparaîtront ici.",
    chooseModelTitle: "Choisis un modèle",
    chooseModelBody:
      "NOVA ne choisit pas à ta place : chaque modèle a son prix et ses capacités. Tu pourras en changer à tout moment.",
    chooseModelAction: "Choisir un modèle",
    currentModel: (name: string) => `Modèle : ${name}`,
    changeModel: "Changer",
    milestoneNote:
      "Fichiers, terminal et missions arrivent au prochain jalon. Pour l'instant, NOVA converse avec les modèles d'OpenRouter : Nomi n'a accès ni à tes fichiers, ni au terminal, ni à Internet.",
    vaultWeak:
      "Aucun trousseau système n'est disponible sur cet appareil : préfère « Cette session uniquement » pour ta clé.",
    vaultUnavailable: "Le chiffrement n'est pas disponible ici : ta clé ne sera gardée que pour cette session.",
  },
  onboarding: {
    eyebrow: "Bienvenue dans NOVA",
    title: "Connecte OpenRouter pour commencer",
    body: "NOVA utilise ta propre clé OpenRouter : tu choisis les modèles et tu gardes la main sur tes dépenses.",
  },
  keySetup: {
    title: "Clé OpenRouter",
    explanation:
      "Ta clé reste sur cet appareil. Chaque message est envoyé à OpenRouter puis au fournisseur qui sert le modèle.",
    fieldLabel: "Clé API OpenRouter",
    fieldPlaceholder: "sk-or-…",
    show: "Afficher la clé",
    hide: "Masquer la clé",
    createKey: "Créer une clé sur openrouter.ai",
    storageLegend: "Où garder la clé ?",
    storageVault: "Coffre du système (recommandé)",
    storageVaultHint: "Chiffrée par le trousseau de ton système. Tu n'auras pas à la ressaisir.",
    storageSession: "Cette session uniquement",
    storageSessionHint: "Gardée en mémoire jusqu'à la fermeture de NOVA, jamais écrite sur le disque.",
    storageWeak: "Enregistrer avec une protection faible",
    storageWeakHint: "Écrite sur le disque, seulement masquée : quelqu'un qui accède à tes fichiers pourrait la lire.",
    weakAcknowledge: "Je comprends que la clé sera seulement masquée, pas vraiment protégée.",
    weakExplanation:
      "Aucun trousseau système n'est disponible (sous Linux, installe par exemple GNOME Keyring ou KWallet). Sans lui, NOVA ne peut pas chiffrer ta clé.",
    unavailableExplanation:
      "Le chiffrement n'est pas disponible sur ce système : la clé sera oubliée à la fermeture de NOVA.",
    submit: "Tester et enregistrer",
    empty: "Colle ta clé pour continuer.",
    verifiedTitle: "Clé vérifiée",
    unverifiedTitle: "Clé enregistrée, mais pas encore vérifiée",
    unverifiedUnreachable: "OpenRouter est injoignable pour l'instant : la clé n'a pas pu être vérifiée.",
    unverifiedRateLimited: "OpenRouter reçoit trop de requêtes et n'a pas pu vérifier la clé pour l'instant.",
    unverifiedServiceError: "Le service OpenRouter a renvoyé une erreur pendant la vérification.",
    unverifiedUnknown: "La clé n'a pas encore pu être vérifiée.",
    unverifiedNext: "Elle est bien enregistrée : teste-la quand tu veux.",
    saved: "Clé enregistrée",
  },
  keyCheck: {
    label: "Libellé",
    noLabel: "sans libellé",
    limit: "Limite de crédit",
    unlimited: "illimitée ou inconnue",
    remaining: "Reste",
    usage: "Consommé",
    tier: "Offre",
    freeTier: "gratuite",
    paidTier: "créditée",
  },
  providers: {
    title: "Fournisseurs",
    description: "OpenRouter donne accès à des centaines de modèles avec une seule clé.",
    status: "État",
    storage: "Stockage",
    keyHint: "Clé",
    keyHintValue: (hint: string) => `••••${hint}`,
    lastChecked: "Dernier test",
    never: "jamais",
    test: "Tester la clé",
    tested: "Test terminé",
    replace: "Remplacer la clé",
    cancelReplace: "Garder la clé actuelle",
    remove: "Retirer la clé de NOVA",
    removeTitle: "Retirer la clé de NOVA ?",
    removeDescription:
      "La clé sera effacée de cet appareil. Elle reste active chez OpenRouter : pour la révoquer, rends-toi sur openrouter.ai/keys.",
    removed: "Clé retirée de NOVA",
    revokeNote: "Retirer la clé l'efface de NOVA, sans la révoquer. La révocation se fait sur openrouter.ai.",
    manageKeys: "Gérer mes clés sur openrouter.ai",
    lastError: "Dernière erreur",
  },
  models: {
    pickerTitle: "Choisir un modèle",
    pickerDescription: "Catalogue en direct d'OpenRouter. Le modèle choisi s'applique au prochain message.",
    searchLabel: "Rechercher un modèle",
    searchPlaceholder: "Nom, identifiant, auteur…",
    filtersLabel: "Filtres",
    filterText: "Texte en entrée et en sortie",
    filterTools: "Outils",
    filterFree: "Gratuits",
    filterDeepSeek: "DeepSeek",
    clearFilters: "Effacer les filtres",
    loading: "Chargement du catalogue…",
    loadFailed: "Le catalogue n'a pas pu être chargé",
    empty: "Aucun modèle ne correspond",
    emptyBody: "Élargis ta recherche ou retire un filtre.",
    freshness: (relative: string) => `Catalogue mis à jour ${relative}`,
    cacheNotice: (relative: string) => `Copie locale du catalogue, mise à jour ${relative}.`,
    refreshFailed: "Actualisation impossible",
    refresh: "Actualiser le catalogue",
    count: (shown: number, total: number) => `${shown} modèle${shown > 1 ? "s" : ""} sur ${total}`,
    context: (tokens: string) => `${tokens} de contexte`,
    contextUnknown: "contexte inconnu",
    priceIn: "Entrée",
    priceOut: "Sortie",
    perMillion: "par million de jetons",
    variable: "variable",
    free: "gratuit",
    capTools: "Outils",
    capStructured: "Sortie structurée",
    capReasoning: "Raisonnement",
    capYes: "oui",
    capNo: "non",
    capUnknown: "?",
    capUnknownTitle: "Le catalogue ne le précise pas",
    expires: (date: string) => `Retrait prévu le ${date}`,
    selected: "Sélectionné",
    select: (name: string) => `Choisir ${name}`,
    noneSelected: "Aucun modèle choisi",
    notInCatalog: "absent du catalogue actuel",
    defaultModel: "Modèle par défaut",
    defaultModelHint: "Utilisé pour les nouvelles conversations.",
    defaultSaved: "Modèle par défaut enregistré",
  },
  chat: {
    you: "Toi",
    nomi: "Nomi",
    messagesLabel: "Messages",
    emptyTitle: "Nouvelle conversation",
    emptyBody: "Écris ton premier message : Nomi te répond avec le modèle choisi.",
    loading: "Chargement de la conversation…",
    loadFailed: "La conversation n'a pas pu être chargée",
    notFound: "Cette conversation n'existe plus.",
    backHome: "Retour à l'accueil",
    thinking: "Nomi réfléchit…",
    reasoning: "Nomi réfléchit… (le modèle raisonne)",
    stopped: "Génération arrêtée",
    interrupted: "Interrompue — le résultat côté fournisseur est incertain",
    retry: "Réessayer",
    relaunch: "Relancer",
    retryIn: (seconds: number) => `Réessayer dans ${seconds} s`,
    providerDetail: "Détail du fournisseur",
    openPrivacy: "Ouvrir la confidentialité",
    httpStatus: (status: number) => `HTTP ${status}`,
    editTitle: "Renommer la conversation",
    modelButton: (name: string) => `Modèle : ${name}`,
    chooseModel: "Choisir un modèle",
    contextToggle: "Contexte",
    scrollToBottom: "Revenir en bas",
    copyCode: "Copier le code",
    copyFailed: "Copie impossible",
    codeLabel: (language: string) => language,
    codePlain: "texte",
    image: (alt: string) => `Image non affichée : ${alt}`,
    imageNoAlt: "sans description",
    linkRefused: "NOVA n'ouvre pas ce lien",
    linkRefusedBody:
      "Seuls les liens de confiance s'ouvrent depuis NOVA. Vérifie l'adresse réelle ci-dessous : le texte du lien peut être trompeur.",
    linkDestination: "Adresse réelle",
    linkCopy: "Copier l'adresse",
    linkCopied: "Adresse copiée",
    linkDismiss: "Fermer",
    usageIn: (tokens: string) => `envoyés : ${tokens}`,
    usageOut: (tokens: string) => `reçus : ${tokens}`,
    usageUnknown: "jetons et coût non communiqués",
    costKnown: (cost: string) => `${cost} constaté`,
    costUnknown: "coût inconnu",
    servedBy: (model: string) => `servi par ${model}`,
    via: (provider: string) => `via ${provider}`,
    announceCompleted: "Réponse terminée",
    announceStopped: "Génération arrêtée",
    announceFailed: (title: string) => `La réponse a échoué : ${title}`,
  },
  composer: {
    label: "Message",
    placeholder: "Écris à Nomi…",
    send: "Envoyer",
    stop: "Arrêter",
    hint: "Entrée pour envoyer · Maj+Entrée pour aller à la ligne",
    stopHint: "Échap pour arrêter la génération",
    noKey: "Ajoute une clé OpenRouter pour envoyer un message.",
    invalidKey: "La clé OpenRouter est refusée : remplace-la pour envoyer un message.",
    noModel: "Choisis un modèle pour envoyer ton message.",
    offline: "Hors ligne : ton message ne partira pas tant que le réseau n'est pas revenu.",
    busy: "Une génération est en cours dans cette conversation.",
    addKey: "Ajouter une clé",
    sendFailed: "Le message n'est pas parti",
  },
  context: {
    title: "Contexte",
    toggle: "Afficher le contexte",
    close: "Fermer le contexte",
    noConversation: "Ouvre une conversation pour voir son modèle, la destination des données et sa consommation.",
    requestedModel: "Modèle demandé",
    nextModel: (name: string) => `Prochain message : ${name}`,
    servedModel: "Modèle servi",
    servedProvider: "Fournisseur",
    destination: "Destination des données",
    destinationValue: (provider: string) => `Envoyé à OpenRouter → ${provider}`,
    providerUnknown: "fournisseur inconnu",
    privacy: "Confidentialité",
    privacyDeny: "Conservation refusée : seuls les fournisseurs qui ne gardent pas tes messages sont utilisés.",
    privacyAllow: "Conservation autorisée : certains fournisseurs peuvent garder ou utiliser tes messages.",
    privacyLink: "Modifier",
    usage: "Consommation",
    usageNone: "Rien de consommé pour l'instant.",
    tokens: (sent: string, received: string) => `${sent} jetons envoyés · ${received} reçus`,
    costObserved: (cost: string) => `${cost} constaté`,
    costAtLeast: (cost: string, count: number) =>
      `au moins ${cost} constaté · ${count} réponse${count > 1 ? "s" : ""} sans coût connu`,
    costUnknown: "coût inconnu",
    catalog: "Catalogue",
    catalogUnknown: "pas encore chargé",
  },
  settings: {
    title: "Réglages",
    sectionsLabel: "Sections des réglages",
    sections: {
      providers: "Fournisseurs",
      models: "Modèles",
      budget: "Budget",
      permissions: "Permissions",
      internet: "Internet",
      audit: "Journal d'audit",
      privacy: "Confidentialité",
      appearance: "Apparence",
      companion: "Compagnon",
      desktop: "Bureau et affichage",
      shortcuts: "Raccourcis",
      diagnostics: "Diagnostics",
    },
    saved: "Réglage enregistré",
    saveFailed: "Le réglage n'a pas été enregistré",
    privacySwitch: "Autoriser les fournisseurs qui conservent les données",
    privacySwitchDescription:
      "Désactivé (recommandé) : OpenRouter n'envoie tes messages qu'aux fournisseurs qui ne les conservent pas et ne s'en servent pas pour entraîner leurs modèles. Certains modèles peuvent alors être indisponibles.",
    leavesTitle: "Ce qui quitte ton appareil",
    leaves: [
      "Les messages de la conversation (l'historique récent) et une consigne système qui présente Nomi.",
      "Ils partent vers OpenRouter, puis vers le fournisseur qui sert le modèle choisi.",
      "Ta clé est transmise à OpenRouter seulement, pour authentifier les requêtes.",
    ],
    staysTitle: "Ce qui reste sur ton appareil",
    stays: [
      "Tes conversations, dans le dossier de données de NOVA.",
      "Ta clé, dans le coffre choisi (ou en mémoire pour une clé de session).",
      "Aucun fichier n'est lu ni envoyé dans cette version.",
    ],
    themeLabel: "Thème",
    themeSystem: "Système",
    themeDark: "Sombre",
    themeLight: "Clair",
    companionVisible: "Afficher Nomi",
    companionVisibleDescription:
      "Masqué, Nomi laisse place à une pastille d'état : tu gardes toutes les informations en texte.",
    motionLabel: "Animations",
    motionSystem: "Système",
    motionReduce: "Réduites",
    motionFull: "Complètes",
    motionDescription: "« Système » suit la préférence de réduction des animations de ton ordinateur.",
    noticesTitle: "Ce que Nomi t'a signalé",
    noticesEmpty: "Rien pour l'instant dans cette session.",
    noticeHeld: "gardé pendant le mode discret",
    shortcutsIntro: "Sur macOS, remplace Ctrl par ⌘.",
    shortcuts: [
      { keys: ["Ctrl", "K"], label: "Ouvrir la palette de commandes" },
      { keys: ["Ctrl", "N"], label: "Nouvelle conversation" },
      { keys: ["Ctrl", ","], label: "Ouvrir les réglages" },
      { keys: ["Entrée"], label: "Envoyer le message" },
      { keys: ["Maj", "Entrée"], label: "Aller à la ligne" },
      { keys: ["Échap"], label: "Arrêter la génération (depuis la zone de saisie)" },
    ],
    diagnostics: {
      version: "Version",
      electron: "Electron",
      platform: "Plateforme",
      packaged: "Application empaquetée",
      yes: "oui",
      no: "non (développement)",
      vault: "Coffre des secrets",
      vaultBackend: (backend: string) => `moteur : ${backend}`,
      dataDir: "Dossier de données",
      logDir: "Dossier des journaux",
      loading: "Lecture des informations…",
      gallery: "Bibliothèque de composants",
      galleryShow: "Afficher la bibliothèque de composants",
      galleryHide: "Masquer la bibliothèque de composants",
    },
  },
  palette: {
    title: "Palette de commandes",
    label: "Commandes",
    placeholder: "Tape une commande…",
    searchPlaceholder: "Rechercher dans les conversations…",
    empty: "Aucune commande ne correspond.",
    emptyConversations: "Aucune conversation trouvée.",
    loadingConversations: "Recherche…",
    groupActions: "Actions",
    groupTheme: "Thème",
    groupConversations: "Conversations",
    newConversation: "Nouvelle conversation",
    searchConversation: "Rechercher une conversation",
    changeModel: "Changer de modèle",
    stop: "Arrêter la génération",
    settings: "Réglages",
    home: "Accueil",
    themeLight: "Thème clair",
    themeDark: "Thème sombre",
    themeSystem: "Thème du système",
    back: "Retour aux commandes",
  },
  layout: {
    skipToContent: "Aller au contenu",
    mainLabel: "Contenu",
  },
  // J2-A atelier surfaces; each block lives in its own module so lanes do not collide.
  atelier: atelierCopy,
  diff: diffCopy,
  extensions: extensionsCopy,
  atelierSettings: atelierSettingsCopy,
} as const;
