// Identifier schemas shared by every IPC request.
import { z } from "zod";

/** Entity ids are UUIDs generated by main. */
export const EntityIdSchema = z.uuid();

/** Model ids look like `author/model-name[:variant]`; kept permissive but bounded. */
export const ModelIdSchema = z
  .string()
  .min(1)
  .max(200)
  .regex(/^[\w.\-~]+\/[\w.\-:~@]+$/, "identifiant de modèle invalide");

/** Host pattern: lowercase domain, optional leading `*.` for subdomains (no scheme, port or path). */
export const HostPatternSchema = z
  .string()
  .min(1)
  .max(253)
  .regex(/^(\*\.)?[a-z0-9-]+(\.[a-z0-9-]+)*$/, "hôte invalide");
