// French copy of the terminal panel (to be merged into copy/fr.ts by the lead: `fr.terminal`).
export const terminalCopy = {
  panelLabel: "Terminal",
  tabsLabel: "Sessions de terminal",
  newSession: "Nouveau terminal",
  emptyTitle: "Aucune session",
  emptyDetail: "Ouvre un terminal dans le dossier du projet.",
  loading: "Ouverture du terminal…",
  unavailableTitle: "Terminal indisponible",
  retry: "Réessayer",
  sessionRegion: (index: number, shell: string) => `Terminal ${index} : ${shell}`,
  escapeHint: "F6 pour sortir du terminal.",
  nomi: "Nomi",
  agentReadOnly: "Session de Nomi en lecture seule : tu vois ses commandes, la saisie est bloquée.",
  takeOver: "Prendre la main",
  running: "En cours",
  exitedOk: "Terminé · code 0",
  exitedCode: (code: number) => `Échec · code ${code}`,
  exitedSignal: "Arrêté",
  exitAnnouncement: (code: number | null) =>
    code === null ? "Le processus a été arrêté." : `Processus terminé avec le code ${code}.`,
  explainError: "Expliquer l'erreur",
  explainSelection: "Expliquer cette sélection",
  clear: "Effacer",
  find: "Chercher",
  findLabel: "Chercher dans le terminal",
  findNext: "Occurrence suivante",
  findPrevious: "Occurrence précédente",
  findClose: "Fermer la recherche",
  close: "Fermer la session",
  closeAgentConfirm: "Nomi utilise cette session. La fermer arrête sa commande.",
  closeConfirm: "Fermer",
  cancel: "Annuler",
  degraded:
    "Accélération graphique indisponible : terminal en mode dégradé (certaines couleurs ne sont pas ajustées).",
  portLost: "La connexion à cette session a été perdue.",
  reconnect: "Reconnecter",
} as const;
